// ═══════ CONVENTIONS ═══════
const CONVENTIONS = [
  {
    id: "kmz",
    desc: "KMZ",
    exampleDoc: "DocumentName",
    ext: "kmz",
    info: "Google Earth project mapping files \u2014 exported KMZ overlays, alignments, and project boundaries.",
    exampleName: "P3_201210-9_ProjectLimits_2025-01-15.kmz",
    title: true,
    designId: false,
    fpidFull: false,
    projectId: true,
    fpidShort: true,
    componentId: false,
    submittalSuffix: false,
    customId: false,
    formattedDate: true
  },
  {
    id: "fdot-prod",
    desc: "FDOT Production Deliverables",
    exampleDoc: "PLANS-XX-SUBDISCIPLINE",
    ext: "pdf",
    info: "Final plan sheet deliverables submitted to FDOT \u2014 one file per discipline, no phase suffix.",
    exampleName: "20121095201-PLANS-01-ROADWAY.pdf",
    title: false,
    designId: false,
    fpidFull: true,
    projectId: false,
    fpidShort: false,
    componentId: true,
    submittalSuffix: false,
    customId: false,
    formattedDate: false
  },
  {
    id: "fdot-prod-ph",
    desc: "FDOT Production Deliverables (Phased)",
    exampleDoc: "PLANS-XX-SUBDISCIPLINE",
    ext: "pdf",
    info: "Same as Production Deliverables but for phased submittals \u2014 includes a submittal phase suffix.",
    exampleName: "20121095201-PLANS-01-ROADWAY-90pct.pdf",
    title: false,
    designId: false,
    fpidFull: true,
    projectId: false,
    fpidShort: false,
    componentId: true,
    submittalSuffix: true,
    customId: false,
    formattedDate: false
  },
  {
    id: "guide",
    desc: "Guide Sign Worksheets",
    exampleDoc: "GuideSignWorksheets",
    ext: "pdf",
    info: "Guide sign design worksheets submitted with the full 11-digit FPID identifier.",
    exampleName: "20121095201_GuideSignWorksheets.pdf",
    title: true,
    designId: false,
    fpidFull: true,
    projectId: false,
    fpidShort: false,
    componentId: false,
    submittalSuffix: false,
    customId: false,
    formattedDate: false
  },
  {
    id: "design",
    desc: "Design Submittal",
    exampleDoc: "DocumentName",
    ext: "pdf",
    info: "Design documents tracked by project, phase, and submittal number \u2014 reports, calculations, memos, and analysis packages.",
    exampleName: "P3-PS-0001.00_PvmtDsgnRpt.pdf",
    title: true,
    designId: true,
    fpidFull: false,
    projectId: false,
    fpidShort: false,
    componentId: false,
    submittalSuffix: false,
    customId: false,
    formattedDate: false
  },
  {
    id: "fpid-doc",
    desc: "FPID Document",
    exampleDoc: "DocumentName",
    ext: "pdf",
    info: "General project documents identified by short FPID \u2014 correspondence, approvals, and miscellaneous deliverables.",
    exampleName: "201210-9_TypSectionPkg.pdf",
    title: true,
    designId: false,
    fpidFull: false,
    projectId: false,
    fpidShort: true,
    componentId: false,
    submittalSuffix: false,
    customId: false,
    formattedDate: false
  },
  {
    id: "permit",
    desc: "Permit Document",
    exampleDoc: "XXXXX-XX",
    ext: "pdf",
    info: "Permit documents filed by agency permit number \u2014 ERP, NPDES, Section 404, Biological Opinions, and dewatering permits.",
    exampleName: "50-12345-P_Permit-SFWMD-ERP.pdf",
    title: false,
    designId: false,
    fpidFull: false,
    projectId: false,
    fpidShort: false,
    componentId: false,
    submittalSuffix: false,
    customId: true,
    formattedDate: false
  }
];

// ═══════ ABBREVIATIONS ═══════
const ABBREVIATIONS = {
  "Alignment": "Algn",
  "Architectural": "Arch",
  "Asbestos Containing Materials": "ACM",
  "Attachment": "Atch",
  "Calculation": "Calc",
  "Calculations": "Calcs",
  "Certificate": "Cert",
  "Certification": "Cert",
  "Cross Section": "Xsec",
  "Cross-Section": "Xsec",
  "Design": "Dsgn",
  "Design Analysis Report": "DAR",
  "Document": "Doc",
  "Documents": "Docs",
  "Drainage": "Drng",
  "Drawing": "Dwg",
  "Drawings": "Dwgs",
  "Elevation": "Elev",
  "Environmental": "Env",
  "Evaluation": "Eval",
  "Existing": "Exist",
  "Geotechnical": "Geotech",
  "Hydraulic": "Hydr",
  "Information": "Info",
  "Inspection": "Insp",
  "Intelligent Transportation System": "ITS",
  "Investigation": "Invstg",
  "Justification": "Just",
  "Landscape": "Lndscpe",
  "Lighting": "Ltg",
  "Maintenance": "Maint",
  "Maximum": "Max",
  "Memorandum": "Memo",
  "Minimum": "Min",
  "Modification": "Mod",
  "Operations": "Ops",
  "Original": "Orig",
  "Package": "Pkg",
  "Pavement": "Pvmt",
  "Phase": "Ph",
  "Preliminary": "Prelim",
  "Profile": "Prof",
  "Quantities": "Qtys",
  "Quantity": "Qty",
  "Report": "Rpt",
  "Requirement": "Req",
  "Requirements": "Reqs",
  "Revision": "Rev",
  "Right-of-Way": "ROW",
  "Roadway": "Rdwy",
  "Schedule": "Sched",
  "Segment": "Seg",
  "Shoulder": "Shldr",
  "Signalization": "Sgnlztn",
  "Standard": "Std",
  "Structure": "Struct",
  "Structures": "Structs",
  "Survey": "Srvy",
  "Temporary": "Temp",
  "Typical": "Typ",
  "Verification": "Vrfctn",
  "Worksheet": "Wksht"
};

// ═══════ PROJECTS ═══════
const PROJECTS = [
  { name: "Project 1", abbr: "P1" },
  { name: "Project 2", abbr: "P2" },
  { name: "Project 3", abbr: "P3" },
  { name: "Project 4", abbr: "P4" },
  { name: "Project 5", abbr: "P5" },
  { name: "Accel Start Seg A", abbr: "PA" },
  { name: "Accel Start Seg B", abbr: "PB" }
];

// ═══════ FPIDS ═══════
const FPIDS = [
  { fpid: "201210-8", desc: "I-4 from east of U.S. 27 to west of S.R. 429", full: "20121085201", project: "Accel Start Seg A" },
  { fpid: "431456-6", desc: "I-4 from west of S.R. 429 to east of World Drive", full: "43145665201", project: "Accel Start Seg B" },
  { fpid: "431456-7", desc: "I-4 from east of World Drive to east of U.S. 192", full: "43145675201", project: "Project 1" },
  { fpid: "445883-1", desc: "Southern Connector (SR 417) AET (M&R)", full: "44588315201", project: "Project 1" },
  { fpid: "445883-2", desc: "Southern Connector (SR 417) AET (Reconstruction)", full: "44588325201", project: "Project 1" },
  { fpid: "431456-3", desc: "I-4 from east of C.R. 532 to west of World Drive", full: "43145635201", project: "Project 2" },
  { fpid: "446581-6", desc: "Poinciana Connector, Greenfield - Ramps to EB I-4", full: "44658165201", project: "Project 2" },
  { fpid: "446581-3", desc: "Poinciana Connector, Modify/Construct I-4 Ramps with SR 429", full: "44658135201", project: "Project 2" },
  { fpid: "201210-9", desc: "I-4 from west of U.S. 27 to west of C.R. 532", full: "20121095201", project: "Project 3" },
  { fpid: "451381-2", desc: "Grandview Pkwy from north of Posner Blvd to Dunson Rd", full: "45138125201", project: "Project 3" },
  { fpid: "431456-2", desc: "I-4 from east of U.S. 192 to east of S.R. 536", full: "43145625201", project: "Project 4" },
  { fpid: "453159-3", desc: "I-4 EB Tube from west of S.R. 536 to west of Universal Blvd", full: "45315935201", project: "Project 4" },
  { fpid: "446581-4", desc: "Poinciana Connector (S.R. 538)", full: "44658145201", project: "Project 5" }
];

// ═══════ SUBMITTAL PHASES ═══════
const SUBMITTAL_PHASES = [
  { desc: "Prelim Engineering - Line and Grade", prefix: "", suffix: "15pct" },
  { desc: "Prelim Engineering - Phase 1", prefix: "", suffix: "30pct" },
  { desc: "Prelim Engineering - Phase 1A", prefix: "", suffix: "30Apct" },
  { desc: "Prelim Engineering - Phase 2", prefix: "", suffix: "45pct" },
  { desc: "Design - Phase Submittal (60%)", prefix: "PS", suffix: "60pct" },
  { desc: "Design - Phase Submittal (90%)", prefix: "PS", suffix: "90pct" },
  { desc: "Design - Final Submittal (100%)", prefix: "FS", suffix: "Final" },
  { desc: "Design - Released for Construction", prefix: "RC", suffix: "RFC" },
  { desc: "Design - Project Documentation", prefix: "PD", suffix: "-" },
  { desc: "Design - Shop Drawing", prefix: "SD", suffix: "-" },
  { desc: "Design - Contract Submittal", prefix: "CS", suffix: "-" },
  { desc: "Design - Courtesy Review", prefix: "CR", suffix: "-" },
  { desc: "Design - Field Correction Request", prefix: "FCR", suffix: "-" },
  { desc: "Design - Request for Information", prefix: "RFI", suffix: "-" },
  { desc: "Design - Request for Modification", prefix: "RFM", suffix: "-" }
];

// ═══════ COMPONENTS ═══════
const COMPONENTS = [
  { name: "Roadway Plans", id: "PLANS-01-ROADWAY" },
  { name: "Signing and Pavement Marking Plans", id: "PLANS-02-SIGNINGMARKING" },
  { name: "Signalization Plans", id: "PLANS-03-SIGNALIZATION" },
  { name: "Intelligent Transportation System (ITS) Plans", id: "PLANS-04-ITS" },
  { name: "Lighting Plans", id: "PLANS-05-LIGHTING" },
  { name: "Landscaping Plans", id: "PLANS-06-LANDSCAPE" },
  { name: "Architectural Plans", id: "PLANS-07-ARCHITECHTURAL" },
  { name: "Structures Plans", id: "PLANS-08-STRUCTURES" },
  { name: "Toll Plans", id: "PLANS-09-TOLLFACILITIES" },
  { name: "Utility Work by Highway Contractor Agreement Plans", id: "PLANS-10-UTILITYWORK" },
  { name: "Roadway Plans - Geotechnical Core Borings", id: "PLANS-01-ROADWAY-COREBORINGS" },
  { name: "Roadway Plans - Verification of Underground Utilities Survey", id: "PLANS-01-ROADWAY-VERIFIEDUTILITIES" },
  { name: "Roadway Plans - Tree Survey", id: "PLANS-01-ROADWAY-TREESURVEY" },
  { name: "CADD Folder", id: "CADD" }
];

// ═══════ PERMITS ═══════
const PERMITS = [
  { name: "Permit (SFWMD ERP)", regex: "\\d{2}-\\d{5}-[a-zA-Z]", prefix: "Permit-SFWMD-ERP", hint: "##-#####-A", example: "50-12345-P", mask: "2 digits, dash, 5 digits, dash, 1 letter" },
  { name: "Permit (SWFWMD ERP)", regex: "^(43-)?\\d{7}$", prefix: "Permit-SWFWMD-ERP", hint: "####### or 43-#######", example: "4301234", mask: "7 digits (optionally prefixed with 43-)" },
  { name: "Permit (USACE Section 404)", regex: "^SAJ-\\d{4}-\\d{5}(\\(.*\\))?$", prefix: "Permit-USACE-404", hint: "SAJ-####-#####", example: "SAJ-2024-00123", mask: "SAJ, dash, 4 digits, dash, 5 digits" },
  { name: "Permit (USFWS Biological Opinion)", regex: "\\b\\d{4}-\\d{7}\\b", prefix: "Permit-USFWS-BO", hint: "####-#######", example: "2024-0012345", mask: "4 digits, dash, 7 digits" }
];

// ═══════ TITLE SUGGESTIONS ═══════
const TITLE_SUGGESTIONS = [
  "ICE Report",
  "Design Variation Package",
  "Design Exception Package",
  "Design Memorandum",
  "Design Variation Memorandum",
  "Correspondence",
  "Lane Repurposing Approval",
  "FAA Determination",
  "Intersection Number Request Form",
  "Contract Time Memorandum",
  "Permit Exemption Letter",
  "Structure Number Request Form",
  "Value Engineering Report",
  "Typical Section Package",
  "Pavement Design Report",
  "AutoTurn Analysis",
  "Superelevation Analysis",
  "Cross Slope Evaluation",
  "Barrier Length of Need Analysis",
  "Sight Distance Analysis",
  "Lane Closure Analysis",
  "Work Zone Speed Study",
  "Summary of Pay Items Report",
  "Cross Section Sheet",
  "Transportation Management Plan",
  "ADA Assessment Report",
  "Roadway Safety Assessment Report",
  "Roadway Operational Assessment Report",
  "Existing Roadway Characteristics Assessment Report",
  "Community Awareness Plan",
  "Express Lanes Separation Treatment Selection Memo",
  "Location Hydraulics Report",
  "Bridge Hydraulics Report",
  "Pond Siting Report",
  "Drainage Report",
  "Base Clearance Water Evaluation Report",
  "Pipe Inspection Report",
  "Attachment to Barrier Calculations",
  "Multi-Post Sign Report",
  "Concept Signing Plan",
  "Signal Warrant Report",
  "Signal Analysis Report",
  "ITS Concept of Operations",
  "ITS Power Design Analysis Report",
  "Express Lanes Systems Engineering Mgmt Plan",
  "Express Lanes Concept of Operations",
  "Voltage Drop Calculations",
  "Lighting Justification Report",
  "Lighting Design Analysis Report",
  "Landscape Maintenance Plan",
  "Bridge Structure Design Calculations",
  "Bridge Load Rating Report",
  "Retaining Wall Design Calculations",
  "Mast Arm Design Calculations",
  "Box Culvert Design Calculations",
  "Ancillary Structures Report",
  "Bridge Development Report",
  "Toll Siting Technical Memorandum",
  "Roadway Geotechnical Report",
  "Structures Geotechnical Report",
  "Intersection Lighting Retrofit Report",
  "Lighting Agency Coordination",
  "Landscape Maintenance Cost Estimate",
  "Irrigation Feasibility Report",
  "Landscape Opportunity Plan",
  "Temporary Detour Bridge Calculations",
  "Temporary Retaining Wall Design Calcs",
  "Temporary Shoring Design Calculations",
  "Overhead Sign Structure Design Calcs",
  "High Mast Lighting Design Calcs",
  "Express Lanes Diagrams and Concept Plans",
  "Tolls Mechanical Design Analysis Report",
  "Tolls Structural Design Analysis Report",
  "Tolls Gantry Design Analysis Report",
  "Tolls Power Design Analysis Report",
  "GTR Deviations",
  "Electrical Calculations",
  "Mechanical Calculations",
  "Plumbing Calculations",
  "Structural Calculations",
  "Water Feature Hydraulic Calculations",
  "Civil Site Design Documentation",
  "Electrical Design Analysis Report",
  "Mechanical Design Analysis Report",
  "Sign Structure Geotechnical Report",
  "Signal Structure Geotechnical Report",
  "ITS Geotechnical Report",
  "Lighting Geotechnical Report",
  "Architectural Geotechnical Investigation Report"
];
