// ═══════ CONVENTIONS ═══════
const CONVENTIONS = [
  {
    id: "kmz",
    desc: "KMZ",
    exampleDoc: "DocumentName",
    ext: "kmz",
    format: "{projectId}_{fpid}_{title}[-{subtitle}]_{date}",
    info: "Google Earth project mapping files \u2014 exported KMZ overlays, alignments, and project boundaries.",
    exampleName: "P3_201210-9_ProjectLimits_2025-01-15.kmz",
    phase: "pre"
  },
  {
    id: "fdot-prod",
    desc: "FDOT Production Deliverables",
    exampleDoc: "PLANS-XX-SUBDISCIPLINE",
    ext: "pdf",
    format: "{fullFpid}-{deliverableId}[-{revisionId}]",
    info: "Final plan sheet deliverables submitted to FDOT \u2014 one file per discipline, no phase suffix.",
    exampleName: "20121095201-PLANS-01-ROADWAY.pdf",
    phase: "pre"
  },
  {
    id: "fdot-prod-ph",
    desc: "FDOT Production Deliverables (Phased)",
    exampleDoc: "PLANS-XX-SUBDISCIPLINE",
    ext: "pdf",
    format: "{fullFpid}-{deliverableId}-{phaseId}",
    info: "Same as Production Deliverables but for phased submittals \u2014 includes a submittal phase suffix.",
    exampleName: "20121095201-PLANS-01-ROADWAY-90pct.pdf",
    phase: "pre"
  },
  {
    id: "guide",
    desc: "Guide Sign Worksheets",
    exampleDoc: "GuideSignWorksheets",
    ext: "pdf",
    format: "{fullFpid}-GuideSignWorksheets",
    info: "Guide sign design worksheets submitted with the full 11-digit FPID identifier.",
    exampleName: "20121095201-GuideSignWorksheets.pdf",
    phase: "pre"
  },
  {
    id: "design",
    desc: "Design Submittal",
    exampleDoc: "DocumentName",
    ext: "pdf",
    format: "{projectId}-{submittalId}.{resubmittalId}-{submittalPrefix}_{title}[-{subtitle}][-{phaseMod}]",
    info: "Design documents tracked by project, phase, and submittal number \u2014 reports, calculations, memos, and analysis packages.",
    exampleName: "P3-0001.00-PS_PvmtDsgnRpt.pdf",
    phase: "post"
  },
  {
    id: "fpid-doc",
    desc: "FPID Document",
    exampleDoc: "DocumentName",
    ext: "pdf",
    format: "{fpid}_{title}[-{subtitle}]",
    info: "General project documents identified by short FPID \u2014 correspondence, approvals, and miscellaneous deliverables.",
    exampleName: "201210-9_TypSectionPkg.pdf",
    phase: "pre"
  },
  {
    id: "permit",
    desc: "Permit Document",
    exampleDoc: "XXXXX-XX",
    ext: "pdf",
    format: "{permitId}_Permit-{permitCode}",
    info: "Permit documents filed by agency permit number \u2014 ERP, NPDES, Section 404, Biological Opinions, and dewatering permits.",
    exampleName: "50-12345-P_Permit-SFWMD-ERP.pdf",
    phase: "pre"
  },
  {
    id: "fpid-doc-ext",
    desc: "FPID Document (External)",
    exampleDoc: "DocumentName",
    ext: "pdf",
    format: "{externalFpid}_{title}[-{subtitle}]",
    info: "External project documents identified by a non-MI4 FPID number in ######-# format.",
    exampleName: "201210-3_NEPADocs.pdf",
    phase: "pre"
  },
  {
    id: "program-doc",
    desc: "Program Document",
    exampleDoc: "DocumentName",
    ext: "pdf",
    format: "MI4_{title}[-{subtitle}]",
    info: "Program-level documents not tied to a specific FPID \u2014 prefixed with MI4.",
    exampleName: "MI4_InterimDrngTypSection.pdf",
    phase: "pre"
  }
];

// ═══════ ABBREVIATIONS ═══════
const ABBREVIATIONS = {
  "Alignment": "Algn",
  "Architectural": "Arch",
  "Asbestos Containing Materials": "ACM",
  "Attachment": "Atch",
  "Calculation": "Calc",
  "Calculations": "Calcs",
  "Certificate": "Cert",
  "Certification": "Cert",
  "Coordination": "Coord",
  "Cross Section": "Xsec",
  "Cross-Section": "Xsec",
  "Design": "Dsgn",
  "Design Analysis Report": "DAR",
  "Distribution": "Dist",
  "Document": "Doc",
  "Documents": "Docs",
  "Drainage": "Drng",
  "Drawing": "Dwg",
  "Drawings": "Dwgs",
  "Elevation": "Elev",
  "Environmental": "Env",
  "Evaluation": "Eval",
  "Existing": "Exist",
  "Existing Roadway Characteristics Assessment Report": "ERCAR",
  "Express Lane": "EL",
  "Express Lanes": "EL",
  "Geotechnical": "Geotech",
  "Information": "Info",
  "Inspection": "Insp",
  "Lead-Based Paint": "LBP",
  "Lighting": "Ltg",
  "Maintenance": "Maint",
  "Maximum": "Max",
  "Memorandum": "Memo",
  "Memorandum of Understanding": "MOU",
  "Minimum": "Min",
  "Modification": "Mod",
  "Original": "Orig",
  "Package": "Pkg",
  "Pavement": "Pvmt",
  "Phase": "Ph",
  "Preliminary": "Prelim",
  "Profile": "Prof",
  "Quantities": "Qtys",
  "Quantity": "Qty",
  "Report": "Rpt",
  "Requirement": "Req",
  "Requirements": "Reqs",
  "Revision": "Rev",
  "Right of Way": "ROW",
  "Right-of-Way": "ROW",
  "Roadway": "Rdwy",
  "Schedule": "Sched",
  "Segment": "Seg",
  "Shoulder": "Shldr",
  "Standard": "Std",
  "Structure": "Struct",
  "Structures": "Structs",
  "Survey": "Srvy",
  "Technical": "Tech",
  "Temporary": "Temp",
  "Transmission": "Trans",
  "Typical": "Typ",
  "Utilities": "Utils",
  "Utility": "Util",
  "Vertical": "Vert"
};

// ═══════ PROJECTS ═══════
const PROJECTS = [
  { name: "Project 1", abbr: "P1" },
  { name: "Project 2", abbr: "P2" },
  { name: "Project 3", abbr: "P3" },
  { name: "Project 4", abbr: "P4" },
  { name: "Project 5", abbr: "P5" },
  { name: "Accel Start Seg A", abbr: "PA" },
  { name: "Accel Start Seg B", abbr: "PB" }
];

// ═══════ FPIDS ═══════
const FPIDS = [
  { fpid: "201210-8", desc: "I-4 (S.R. 400) from east of U.S. 27 to west of S.R. 429", full: "20121085201", project: "Accel Start Seg A" },
  { fpid: "431456-6", desc: "I-4 (S.R. 400) from west of S.R. 429 to east of World Drive", full: "43145665201", project: "Accel Start Seg B" },
  { fpid: "431456-7", desc: "I-4 (S.R. 400) from east of World Drive to east of U.S. 192", full: "43145675201", project: "Project 1" },
  { fpid: "445883-1", desc: "Southern Connector (SR 417) AET (M&R)", full: "44588315201", project: "Project 1" },
  { fpid: "445883-2", desc: "Southern Connector (SR 417) AET (Reconstruction)", full: "44588325201", project: "Project 1" },
  { fpid: "431456-3", desc: "I-4 (S.R. 400) from east of C.R. 532 to west of World Drive", full: "43145635201", project: "Project 2" },
  { fpid: "446581-6", desc: "Poinciana Connector, Greenfield - Ramps to Eastbound I-4", full: "44658165201", project: "Project 2" },
  { fpid: "446581-3", desc: "Poinciana Connector, Modify/Construct I-4 Ramps with SR 429", full: "44658135201", project: "Project 2" },
  { fpid: "201210-9", desc: "I-4 (S.R. 400) from west of U.S. 27 to west of C.R. 532", full: "20121095201", project: "Project 3" },
  { fpid: "451381-2", desc: "Grandview Parkway from north of Posner Boulevard to Dunson Road", full: "45138125201", project: "Project 3" },
  { fpid: "431456-2", desc: "I-4 (S.R. 400) from east of U.S. 192 to east of S.R. 536", full: "43145625201", project: "Project 4" },
  { fpid: "453159-3", desc: "I-4 (S.R. 400) Eastbound Tube from west of S.R. 536 to west of Universal Boulevard", full: "45315935201", project: "Project 4" },
  { fpid: "446581-4", desc: "Poinciana Connector (S.R. 538)", full: "44658145201", project: "Project 5" }
];

// ═══════ SUBMITTAL PHASES ═══════
const SUBMITTAL_PHASES = [
  { desc: "Prelim Engineering - Line and Grade", prefix: "", defaultPhase: "15pct" },
  { desc: "Prelim Engineering - Phase 1", prefix: "", defaultPhase: "30pct" },
  { desc: "Prelim Engineering - Phase 1A", prefix: "", defaultPhase: "30Apct" },
  { desc: "Prelim Engineering - Phase 2", prefix: "", defaultPhase: "45pct" },
  { desc: "Design - Phase Submittal (90%)", prefix: "PS", defaultPhase: "90pct", modifiers: ["30pct", "60pct"] },
  { desc: "Design - Final Submittal (100%)", prefix: "FS", defaultPhase: "Final", modifiers: ["RFC"] },
  { desc: "Design - Project Documentation", prefix: "PD", defaultPhase: "-" },
  { desc: "Design - Shop Drawing", prefix: "SD", defaultPhase: "-" },
  { desc: "Design - Contract Submittal", prefix: "CS", defaultPhase: "-" },
  { desc: "Design - Courtesy Review", prefix: "CR", defaultPhase: "-" },
  { desc: "Design - Field Correction Request", prefix: "FCR", defaultPhase: "-" },
  { desc: "Design - Request for Information", prefix: "RFI", defaultPhase: "-" },
  { desc: "Design - Request for Modification", prefix: "RFM", defaultPhase: "-" }
];

// ═══════ COMPONENTS ═══════
const COMPONENTS = [
  { name: "Roadway Plans", id: "PLANS-01-ROADWAY" },
  { name: "Signing and Pavement Marking Plans", id: "PLANS-02-SIGNINGMARKING" },
  { name: "Signalization Plans", id: "PLANS-03-SIGNALIZATION" },
  { name: "Intelligent Transportation System (ITS) Plans", id: "PLANS-04-ITS" },
  { name: "Lighting Plans", id: "PLANS-05-LIGHTING" },
  { name: "Landscaping Plans", id: "PLANS-06-LANDSCAPE" },
  { name: "Architectural Plans", id: "PLANS-07-ARCHITECHTURAL" },
  { name: "Structures Plans", id: "PLANS-08-STRUCTURES" },
  { name: "Toll Plans", id: "PLANS-09-TOLLFACILITIES" },
  { name: "Utility Work by Highway Contractor Agreement Plans", id: "PLANS-10-UTILITYWORK" },
  { name: "Roadway Plans - Geotechnical Core Borings", id: "PLANS-01-ROADWAY-COREBORINGS" },
  { name: "Roadway Plans - Verification of Underground Utilities Survey", id: "PLANS-01-ROADWAY-VERIFIEDUTILITIES" },
  { name: "Roadway Plans - Tree Survey", id: "PLANS-01-ROADWAY-TREESURVEY" },
  { name: "CADD Folder", id: "CADD" }
];

// ═══════ PERMITS ═══════
const PERMITS = [
  { name: "Permit (SFWMD ERP)", regex: "\\d{2}-\\d{5}-[a-zA-Z]", code: "SFWMD-ERP", prefix: "Permit-SFWMD-ERP", hint: "##-#####-A", example: "50-12345-P", mask: "2 digits, dash, 5 digits, dash, 1 letter" },
  { name: "Permit (SWFWMD ERP)", regex: "^(43-)?\\d{7}$", code: "SWFWMD-ERP", prefix: "Permit-SWFWMD-ERP", hint: "####### or 43-#######", example: "4301234", mask: "7 digits (optionally prefixed with 43-)" },
  { name: "Permit (USACE Section 404)", regex: "^SAJ-\\d{4}-\\d{5}(\\(.*\\))?$", code: "USACE-404", prefix: "Permit-USACE-404", hint: "SAJ-####-#####", example: "SAJ-2024-00123", mask: "SAJ, dash, 4 digits, dash, 5 digits" },
  { name: "Permit (USFWS Biological Opinion)", regex: "\\b\\d{4}-\\d{7}\\b", code: "USFWS-BO", prefix: "Permit-USFWS-BO", hint: "####-#######", example: "2024-0012345", mask: "4 digits, dash, 7 digits" }
];

// ═══════ TITLE SUGGESTIONS ═══════
const TITLE_SUGGESTIONS = [
  "ICE Report",
  "Design Variation Package",
  "Design Exception Package",
  "Design Memorandum",
  "Design Variation Memorandum",
  "Correspondence",
  "Lane Repurposing Approval",
  "FAA Determination",
  "Intersection Number Request Form",
  "Contract Time Memorandum",
  "Permit Exemption Letter",
  "Structure Number Request Form",
  "Value Engineering Report",
  "Typical Section Package",
  "Pavement Design Report",
  "AutoTurn Analysis",
  "Superelevation Analysis",
  "Cross Slope Evaluation",
  "Barrier Length of Need Analysis",
  "Sight Distance Analysis",
  "Lane Closure Analysis",
  "Work Zone Speed Study",
  "Summary of Pay Items Report",
  "Cross Section Sheet",
  "Transportation Management Plan",
  "ADA Assessment Report",
  "Roadway Safety Assessment Report",
  "Roadway Operational Assessment Report",
  "Existing Roadway Characteristics Assessment Report",
  "Community Awareness Plan",
  "Express Lanes Separation Treatment Selection Memo",
  "Location Hydraulics Report",
  "Bridge Hydraulics Report",
  "Pond Siting Report",
  "Drainage Report",
  "Base Clearance Water Evaluation Report",
  "Pipe Inspection Report",
  "Attachment to Barrier Calculations",
  "Multi-Post Sign Report",
  "Concept Signing Plan",
  "Signal Warrant Report",
  "Signal Analysis Report",
  "ITS Concept of Operations",
  "ITS Power Design Analysis Report",
  "Express Lanes Systems Engineering Mgmt Plan",
  "Express Lanes Concept of Operations",
  "Voltage Drop Calculations",
  "Lighting Justification Report",
  "Lighting Design Analysis Report",
  "Landscape Maintenance Plan",
  "Bridge Structure Design Calculations",
  "Bridge Load Rating Report",
  "Retaining Wall Design Calculations",
  "Mast Arm Design Calculations",
  "Box Culvert Design Calculations",
  "Ancillary Structures Report",
  "Bridge Development Report",
  "Toll Siting Technical Memorandum",
  "Roadway Geotechnical Report",
  "Structures Geotechnical Report",
  "Intersection Lighting Retrofit Report",
  "Lighting Agency Coordination",
  "Landscape Maintenance Cost Estimate",
  "Irrigation Feasibility Report",
  "Landscape Opportunity Plan",
  "Temporary Detour Bridge Calculations",
  "Temporary Retaining Wall Design Calcs",
  "Temporary Shoring Design Calculations",
  "Overhead Sign Structure Design Calcs",
  "High Mast Lighting Design Calcs",
  "Express Lanes Diagrams and Concept Plans",
  "Tolls Mechanical Design Analysis Report",
  "Tolls Structural Design Analysis Report",
  "Tolls Gantry Design Analysis Report",
  "Tolls Power Design Analysis Report",
  "GTR Deviations",
  "Electrical Calculations",
  "Mechanical Calculations",
  "Plumbing Calculations",
  "Structural Calculations",
  "Water Feature Hydraulic Calculations",
  "Civil Site Design Documentation",
  "Electrical Design Analysis Report",
  "Mechanical Design Analysis Report",
  "Sign Structure Geotechnical Report",
  "Signal Structure Geotechnical Report",
  "ITS Geotechnical Report",
  "Lighting Geotechnical Report",
  "Sub-Surface Utility Location Form (mast arm)",
  "Architectural Geotechnical Investigation Report",
  "Erosion Control Plan",
  "Air Quality Analysis Technical Memorandum",
  "Concept of Operations",
  "Cultural Resource Assessment",
  "Contamination Screening Evaluation Report",
  "Conceptual Stage Relocation Plan",
  "Endangered Species Biological Assessment",
  "Noise Study Report",
  "Preliminary Engineering Report",
  "Pavement Type Selection Report",
  "Systems Access Modification Report",
  "Utility Impact Report",
  "Wetland Evaluation Report"
];

// ═══════ TITLE PSEE FOLDERS ═══════
const TITLE_PSEE_MAP = {
  "ICE Report": "Approvals",
  "Design Variation Package": "Approvals",
  "Design Exception Package": "Approvals",
  "Design Memorandum": "Approvals",
  "Design Variation Memorandum": "Approvals",
  "Correspondence": "Approvals",
  "Lane Repurposing Approval": "Approvals",
  "FAA Determination": "Approvals",
  "Intersection Number Request Form": "Approvals",
  "Contract Time Memorandum": "Approvals",
  "Permit Exemption Letter": "Approvals",
  "Structure Number Request Form": "Approvals",
  "Value Engineering Report": "Approvals",
  "Typical Section Package": "Roadway",
  "Pavement Design Report": "Roadway",
  "AutoTurn Analysis": "Roadway",
  "Superelevation Analysis": "Roadway",
  "Cross Slope Evaluation": "Roadway",
  "Barrier Length of Need Analysis": "Roadway",
  "Sight Distance Analysis": "Roadway",
  "Lane Closure Analysis": "Roadway",
  "Work Zone Speed Study": "Roadway",
  "Summary of Pay Items Report": "Roadway",
  "Cross Section Sheet": "Roadway",
  "Transportation Management Plan": "Roadway",
  "ADA Assessment Report": "Roadway",
  "Roadway Safety Assessment Report": "Roadway",
  "Roadway Operational Assessment Report": "Roadway",
  "Existing Roadway Characteristics Assessment Report": "Roadway",
  "Community Awareness Plan": "Roadway",
  "Express Lanes Separation Treatment Selection Memo": "Roadway",
  "Location Hydraulics Report": "Drainage",
  "Bridge Hydraulics Report": "Drainage",
  "Pond Siting Report": "Drainage",
  "Drainage Report": "Drainage",
  "Base Clearance Water Evaluation Report": "Drainage",
  "Pipe Inspection Report": "Drainage",
  "Attachment to Barrier Calculations": "S&PM",
  "Multi-Post Sign Report": "S&PM",
  "Concept Signing Plan": "S&PM",
  "Sub-Surface Utility Location Form (mast arm)": "Signals",
  "Signal Warrant Report": "Signals",
  "Signal Analysis Report": "Signals",
  "ITS Concept of Operations": "ITS",
  "ITS Power Design Analysis Report": "ITS",
  "Express Lanes Systems Engineering Mgmt Plan": "ITS",
  "Express Lanes Concept of Operations": "ITS",
  "Voltage Drop Calculations": "Lighting",
  "Lighting Justification Report": "Lighting",
  "Lighting Design Analysis Report": "Lighting",
  "Intersection Lighting Retrofit Report": "Lighting",
  "Lighting Agency Coordination": "Lighting",
  "Landscape Maintenance Plan": "Landscape",
  "Landscape Maintenance Cost Estimate": "Landscape",
  "Irrigation Feasibility Report": "Landscape",
  "Landscape Opportunity Plan": "Landscape",
  "Bridge Structure Design Calculations": "Structures",
  "Temporary Detour Bridge Calculations": "Structures",
  "Bridge Load Rating Report": "Structures",
  "Temporary Retaining Wall Design Calcs": "Structures",
  "Temporary Shoring Design Calculations": "Structures",
  "Retaining Wall Design Calculations": "Structures",
  "Overhead Sign Structure Design Calcs": "Structures",
  "Mast Arm Design Calculations": "Structures",
  "Box Culvert Design Calculations": "Structures",
  "High Mast Lighting Design Calcs": "Structures",
  "Ancillary Structures Report": "Structures",
  "Bridge Development Report": "Structures",
  "Toll Siting Technical Memorandum": "Tolls",
  "Express Lanes Diagrams and Concept Plans": "Tolls",
  "Tolls Mechanical Design Analysis Report": "Tolls",
  "Tolls Structural Design Analysis Report": "Tolls",
  "Tolls Gantry Design Analysis Report": "Tolls",
  "Tolls Power Design Analysis Report": "Tolls",
  "GTR Deviations": "Tolls",
  "Electrical Calculations": "Architectural",
  "Mechanical Calculations": "Architectural",
  "Plumbing Calculations": "Architectural",
  "Structural Calculations": "Architectural",
  "Water Feature Hydraulic Calculations": "Architectural",
  "Civil Site Design Documentation": "Architectural",
  "Electrical Design Analysis Report": "Architectural",
  "Mechanical Design Analysis Report": "Architectural",
  "Roadway Geotechnical Report": "Geotech",
  "Sign Structure Geotechnical Report": "Geotech",
  "Signal Structure Geotechnical Report": "Geotech",
  "ITS Geotechnical Report": "Geotech",
  "Lighting Geotechnical Report": "Geotech",
  "Structures Geotechnical Report": "Geotech",
  "Architectural Geotechnical Investigation Report": "Geotech"
};

// ═══════ TITLE SWEPT FOLDERS ═══════
const TITLE_SWEPT_MAP = {
  "Air Quality Analysis Technical Memorandum": "Air Quality",
  "Concept of Operations": "Engineering",
  "Cultural Resource Assessment": "Cultural Resources",
  "Contamination Screening Evaluation Report": "Contamination",
  "Conceptual Stage Relocation Plan": "Sociocultural Effects",
  "Endangered Species Biological Assessment": "Protected Species",
  "Noise Study Report": "Noise",
  "Preliminary Engineering Report": "Engineering",
  "Pavement Type Selection Report": "Engineering",
  "Systems Access Modification Report": "Engineering",
  "Utility Impact Report": "Utilities",
  "Wetland Evaluation Report": "Wetlands"
};

// ═══════ FIELDS ═══════
const FIELDS = [
  { id: "title", name: "Title", type: "text" },
  { id: "subtitle", name: "Subtitle", type: "text" },
  { id: "fpid", name: "FPID", type: "select", validates: "FPIDS", validatesKey: "fpid" },
  { id: "externalFpid", name: "External FPID", type: "number", regex: "^\\d{1,7}$", format: "000000-0" },
  { id: "project", name: "Project", type: "select", validates: "PROJECTS", validatesKey: "name" },
  { id: "deliverable", name: "Deliverable", type: "select", validates: "COMPONENTS", validatesKey: "name" },
  { id: "permit", name: "Permit", type: "select", validates: "PERMITS", validatesKey: "name" },
  { id: "permitId", name: "Permit ID", type: "text", validatesAgainst: "PERMITS.regex", validatesVia: "permit" },
  { id: "submittalId", name: "Submittal ID", type: "number", regex: "^\\d{1,4}$", format: "0000" },
  { id: "resubmittalId", name: "Resubmittal ID", type: "number", regex: "^\\d{1,2}$", format: "00" },
  { id: "revisionId", name: "Revision ID", type: "number", regex: "^\\d{1,2}$", format: "REV00" },
  { id: "date", name: "Date", type: "date" },
  { id: "submittal", name: "Submittal", type: "select", validates: "SUBMITTAL_PHASES", validatesKey: "desc" },
  { id: "fullFpid", name: "Full FPID", type: "lookup", source: "FPIDS", sourceKey: "fpid", via: "fpid", returns: "full" },
  { id: "deliverableId", name: "Deliverable ID", type: "lookup", source: "COMPONENTS", sourceKey: "name", via: "deliverable", returns: "id" },
  { id: "phaseId", name: "Phase ID", type: "lookup", source: "SUBMITTAL_PHASES", sourceKey: "desc", via: "submittal", returns: "defaultPhase" },
  { id: "projectId", name: "Project ID", type: "lookup", source: "PROJECTS", sourceKey: "name", via: "project", returns: "abbr" },
  { id: "submittalPrefix", name: "Submittal Prefix", type: "lookup", source: "SUBMITTAL_PHASES", sourceKey: "desc", via: "submittal", returns: "prefix" },
  { id: "permitCode", name: "Permit Code", type: "lookup", source: "PERMITS", sourceKey: "name", via: "permit", returns: "code" },
  { id: "phaseMod", name: "Phase Modifier", type: "text" }
];

// ═══════ RULES ═══════
const RULES = [
  { convention: "kmz", field: "fpid", required: true },
  { convention: "kmz", field: "title", required: true },
  { convention: "kmz", field: "subtitle", required: false },
  { convention: "kmz", field: "date", required: true },
  { convention: "kmz", field: "projectId" },
  { convention: "fdot-prod", field: "fpid", required: true },
  { convention: "fdot-prod", field: "deliverable", required: true },
  { convention: "fdot-prod", field: "revisionId", required: false },
  { convention: "fdot-prod", field: "fullFpid" },
  { convention: "fdot-prod", field: "deliverableId" },
  { convention: "fdot-prod-ph", field: "fpid", required: true },
  { convention: "fdot-prod-ph", field: "deliverable", required: true },
  { convention: "fdot-prod-ph", field: "submittal", required: true },
  { convention: "fdot-prod-ph", field: "fullFpid" },
  { convention: "fdot-prod-ph", field: "deliverableId" },
  { convention: "fdot-prod-ph", field: "phaseId" },
  { convention: "guide", field: "fpid", required: true },
  { convention: "guide", field: "fullFpid" },
  { convention: "design", field: "project", required: true },
  { convention: "design", field: "submittal", required: true },
  { convention: "design", field: "submittalId", required: true },
  { convention: "design", field: "resubmittalId", required: false },
  { convention: "design", field: "title", required: true },
  { convention: "design", field: "subtitle", required: false },
  { convention: "design", field: "phaseMod", required: false },
  { convention: "design", field: "projectId" },
  { convention: "design", field: "submittalPrefix" },
  { convention: "fpid-doc", field: "fpid", required: true },
  { convention: "fpid-doc", field: "title", required: true },
  { convention: "fpid-doc", field: "subtitle", required: false },
  { convention: "permit", field: "permit", required: true },
  { convention: "permit", field: "permitId", required: true },
  { convention: "permit", field: "permitCode" },
  { convention: "fpid-doc-ext", field: "externalFpid", required: true },
  { convention: "fpid-doc-ext", field: "title", required: true },
  { convention: "fpid-doc-ext", field: "subtitle", required: false },
  { convention: "program-doc", field: "title", required: true },
  { convention: "program-doc", field: "subtitle", required: false }
];
